ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT false;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PENDING';

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS first_login_required BOOLEAN DEFAULT false;
